### ISSUE TITLE
Allow requesting payments with `with_virtualbeneficiary` parameter

### ISSUE THREAD

**Issue by bobmaerten** [Fintecture/fintecture-sdk-ruby#22] opened 2023-05-03 08:34 UTC
In order to implement Reconciled transfer, it would be nice to have an optional parameter in the payments API as mentioned in https://doc.fintecture.com/docs/reconciled-transfer#payment-following-through-the-api

i.e.
```ruby
# payments (session_id = nil, with_virtualbeneficiary: false)
#       session_id: string
#       with_virtualbeneficiary: boolean

response = pis_client.payments 
OR
response = pis_client.payments "7f47d3675f5d4964bc416b43af63b06e"
OR
response = pis_client.payments "7f47d3675f5d4964bc416b43af63b06e", with_virtualbeneficiary: true
```

**Comment by xlaumonier-fintecture** [comment] 2023-06-01 08:53
@bobmaerten Hello, we implemented the with_virtualbeneficiary parameter in latest 0.6.0 version (https://rubygems.org/gems/fintecture). Please let me know whether it all work as intended so I can close this ticket.

Have a good day,
XL

**Closed** 2023-06-26 09:42 UTC
